In [1]:

print('   FELIZ NAVIDAD MTF')
print('         *')
print('        ***')
print('       *****')
print('      *******')
print('     *********')
print('    ***********')
print('   *************')
print('  ***************')
print(' *****************')
print('*******************')
print('       *****')
print('       *****')
print('       *****')
print('   *************')



   FELIZ NAVIDAD MTF
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
       *****
       *****
       *****
   *************


In [2]:
datos =[['ID','EDAD','SEXO'],[1,30,'M'],[2,25,'F']]

In [3]:
datos

[['ID', 'EDAD', 'SEXO'], [1, 30, 'M'], [2, 25, 'F']]

In [4]:
import numpy as np
d = np.array(datos)


In [5]:
d

array([['ID', 'EDAD', 'SEXO'],
       ['1', '30', 'M'],
       ['2', '25', 'F']], dtype='<U11')

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((5,5))+9

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [8]:
np.ones((5,5))*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [9]:
np.ones((5,5))+(9/2)

array([[5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5]])

In [10]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.rand(5,5)

array([[0.24056586, 0.92926849, 0.84585417, 0.95559647, 0.74071444],
       [0.98533875, 0.52322842, 0.25995208, 0.09868824, 0.22497029],
       [0.0263882 , 0.53980975, 0.86591476, 0.86943431, 0.65851825],
       [0.67599948, 0.3589026 , 0.78756652, 0.66003247, 0.3268989 ],
       [0.73496613, 0.57471938, 0.1999918 , 0.10492974, 0.39332714]])

In [12]:
#n para negativos y positivos
np.random.randn(5,5)

array([[-1.45627357,  1.0466776 , -0.58635656, -0.34664514,  1.53465394],
       [-0.52158094,  1.2411562 , -0.59235586, -1.62336084,  0.6269831 ],
       [-1.50062312,  0.33249222,  0.82404206,  2.1044073 , -0.9956427 ],
       [-0.06861622, -0.08200551, -0.30690243,  0.57566347, -0.29583841],
       [-0.23604071, -0.31267986, -0.46580115, -0.58603049,  0.09626216]])

## Series

In [13]:
import pandas as pd

C:\Users\hp\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\hp\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
C:\Users\hp\AppData\Local\Temp/ipykernel_22308/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [14]:
labels = ['a','b','c']
my_list = [10,20,30]
Arr = np.array(my_list)
d = {'a':10,'b':20,'c':30}

In [15]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [16]:
pd.Series(Arr)

0    10
1    20
2    30
dtype: int32

In [17]:
pd.Series(data=Arr,index=labels)

a    10
b    20
c    30
dtype: int32

In [18]:
series1 = pd.Series([1,2,3,4], index = ['USA','GERMANY','USSR','JAPAN'])
series1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [19]:
series1['GERMANY']

2

In [20]:
series2 = pd.Series([1,4,5,6], index = ['USA','GERMANY','ITALY','JAPAN'])
series2

USA        1
GERMANY    4
ITALY      5
JAPAN      6
dtype: int64

In [21]:
# search and sum the matches
series1 + series2

GERMANY     6.0
ITALY       NaN
JAPAN      10.0
USA         2.0
USSR        NaN
dtype: float64

### Data Frame

In [22]:
from numpy.random import randn
np.random.seed(101)

In [23]:
rand_mat =randn(5,4)
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [24]:
df = pd.DataFrame(data=rand_mat)
df

0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [25]:
df =pd.DataFrame(data=rand_mat, index = ['A','B','C','D','E'])
df

0         1         2         3
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
#OR

df =pd.DataFrame(data=rand_mat,index='A B C D E'.split())
df

0         1         2         3
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
df = pd.DataFrame(data = rand_mat, index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [29]:
df[['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [30]:
my_list = ['W','Y']
df[my_list]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [31]:
#creat a new column
df['NEW'] = df['W'] + df['Y']
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [32]:
#drop column
df.drop('NEW',axis=1,inplace = True)
#or df = df.drop('NEW',axis=1)

In [33]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [34]:
df.loc['A']
#SELECT RANGES df.loc['A','E']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [35]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [36]:
df.loc[['A','B'],['Y','Z']]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965

In [37]:
df.drop('A')
# df.drop('A', inplace = True)

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [39]:
df >0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [40]:
df_boolean = df > 0
df_boolean

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [41]:
df[df_boolean]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [43]:
#filtro de un valor
df[df['W']>1]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [44]:
# orden asc y desc
df.sort_values(by= 'Z',ascending = False)

W         X         Y         Z
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
B  0.651118 -0.319318 -0.848077  0.605965
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001

In [45]:
df.sort_values(by='Z', ascending = True)

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
E  0.190794  1.978757  2.605967  0.683509
D  0.188695 -0.758872 -0.933237  0.955057

In [46]:
#condicional con filtros
#for pandas and is &, and or is |
df[(df['W'] > 2) & (df['Z'] > 0)]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [47]:
#show index
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [48]:
#CREATE A NEW COLUMN
new_ind = 'CA NY WY OR CO'.split()
df['States'] = new_ind
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [49]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

### MISSING DATA

In [50]:
#MISSING DATA
df2 = pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})
df2

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [51]:
#DROP MISSING DATA
df2.dropna()

A    B  C
0  1.0  5.0  1

In [52]:
df2.dropna(axis=1)

C
0  1
1  2
2  3

In [53]:
#drop the row al menos la cantidad de errores que quieras
df2.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [54]:
# REEMPLAZAR VALORES PERDIDOS
df2.fillna(value=0)


A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [55]:
df2.mean()

A    1.5
B    5.0
C    2.0
dtype: float64

In [56]:
df2.fillna(df2.mean())

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [57]:
df2['A'].fillna(value=df2['A'].mean(), inplace =True)

C:\Users\hp\AppData\Local\Temp/ipykernel_22308/4034328332.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['A'].fillna(value=df2['A'].mean(), inplace =True)


In [58]:
df2

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

### GROUP BY OPERATION and COMMON OPERATIONS

In [59]:
df3 = pd.DataFrame({'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
                   'Person': ['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
                   'Sales': [200,120,340,124,243,350]})
df3

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [61]:
df3.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [62]:
df3.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [63]:
df3['Company'].unique()

array(['GOOG', 'MSFT', 'FB'], dtype=object)

In [64]:
len(df3['Company'].unique())

3

In [65]:
df3['Company'].nunique()

3

In [66]:
df3['Company'].value_counts()

Company
GOOG    2
MSFT    2
FB      2
Name: count, dtype: int64

In [67]:
df3

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [68]:
def times_two(number):
    return number*2

In [69]:
df3['new'] = df3['Sales'].apply(times_two)
df3

Company   Person  Sales  new
0    GOOG      Sam    200  400
1    GOOG  Charlie    120  240
2    MSFT      Amy    340  680
3    MSFT  Vanessa    124  248
4      FB     Carl    243  486
5      FB    Sarah    350  700